"""
build_defense_stats.py
Extracts individual defensive player production from play-by-play (sacks,
interceptions - extend later with more event types) and produces two things:

1. player_defense_value.csv - each defender's own blended, portable career
   value (recency-weighted across the last 2 seasons), keyed by player_id.
   This follows the player wherever they go, same principle as our offensive
   player stats already do.

2. team_historical_defense_value.csv - for each team, the sum of defensive
   value actually generated BY THAT TEAM'S players in 2024-2025. This
   represents "how much of team_stats.csv's defensive rating came from these
   specific people" - i.e., what auto_defense_adjustments.py needs to know
   in order to tell whether this year's roster is stronger or weaker than
   the personnel who actually produced last year's number.

EVENT WEIGHTS (documented, tunable): sacks and interceptions are weighted
highest since they're the most game-impactful defensive events with the
clearest causal link to points prevented. These weights are a reasonable
starting point, not backtested - same caveat as our other heuristic
constants elsewhere in this project.
"""

import pandas as pd
import numpy as np
import os

RAW_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "raw")
PROCESSED_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "processed")

EVENT_WEIGHTS = {
    "sack": 3.0,
    "interception": 3.0,
}

SEASON_RECENCY_WEIGHT = {0: 1.0, 1: 0.5}  # 0 = most recent season

def load_pbp():
    path = os.path.join(RAW_DIR, "pbp_combined.parquet")
    return pd.read_parquet(path)

def extract_defensive_events(pbp):
    """
    Long-format table: one row per (season, team, player_id, event_type).
    Handles the columns nflverse actually provides for each event type.
    """
    events = []

    if "sack_player_id" in pbp.columns:
        sacks = pbp[pbp["sack"] == 1].dropna(subset=["sack_player_id"])
        for _, r in sacks.iterrows():
            events.append({"season": r["season"], "team": r["defteam"], "player_id": r["sack_player_id"],
                           "player_name": r.get("sack_player_name", r["sack_player_id"]), "event": "sack"})

    if "interception_player_id" in pbp.columns:
        ints = pbp[pbp.get("interception", 0) == 1].dropna(subset=["interception_player_id"])
        for _, r in ints.iterrows():
            events.append({"season": r["season"], "team": r["defteam"], "player_id": r["interception_player_id"],
                           "player_name": r.get("interception_player_name", r["interception_player_id"]), "event": "interception"})

    return pd.DataFrame(events)

def compute_player_season_value(events):
    """Weighted defensive value per player per season per team."""
    events = events.copy()
    events["weight"] = events["event"].map(EVENT_WEIGHTS)
    grouped = events.groupby(["season", "team", "player_id", "player_name"])["weight"].sum().reset_index()
    grouped = grouped.rename(columns={"weight": "defensive_value"})
    return grouped

def season_weight(season, reference_season):
    """Weight based on how many years back from the REFERENCE season this is -
    not the player's own data availability. A player with data in only 2024
    (none in 2025) should be treated as having a real, missing 2025 (=0),
    not as if their 2024 figure were the most recent season."""
    years_back = reference_season - season
    return SEASON_RECENCY_WEIGHT.get(years_back, 0.25)

def blend_player_career_value(player_season_value, reference_season):
    """
    Each player's portable, recency-weighted career defensive value -
    follows the player_id regardless of which team they generated it for.
    Missing seasons are treated as 0 production, not skipped, so a player
    who only shows up in one season is correctly discounted rather than
    having that lone season miscounted as "most recent."
    """
    all_seasons = sorted(player_season_value["season"].unique(), reverse=True)

    rows = []
    for player_id, g in player_season_value.groupby("player_id"):
        season_totals = g.groupby("season")["defensive_value"].sum().reindex(all_seasons, fill_value=0.0)
        weights = [season_weight(s, reference_season) for s in season_totals.index]
        blended_value = np.average(season_totals.values, weights=weights)
        rows.append({"player_id": player_id, "player_name": g.iloc[0]["player_name"], "career_defensive_value": blended_value})

    return pd.DataFrame(rows)

def compute_team_historical_value(player_season_value, reference_season):
    """
    Blended defensive value generated FOR each team, using the same
    fixed-season-year weighting as player blending (see blend_player_career_value)
    so the two are on a directly comparable scale.
    """
    team_season_totals = player_season_value.groupby(["team", "season"])["defensive_value"].sum().reset_index()
    all_seasons = sorted(player_season_value["season"].unique(), reverse=True)

    rows = []
    for team, g in team_season_totals.groupby("team"):
        totals = g.set_index("season")["defensive_value"].reindex(all_seasons, fill_value=0.0)
        weights = [season_weight(s, reference_season) for s in totals.index]
        blended = np.average(totals.values, weights=weights)
        rows.append({"team": team, "historical_defensive_value": blended})

    return pd.DataFrame(rows)

def main():
    print("Loading play-by-play...")
    pbp = load_pbp()

    print("Extracting defensive events (sacks, interceptions)...")
    events = extract_defensive_events(pbp)
    print(f"  {len(events)} defensive events attributed to individual players")

    if events.empty:
        print("  No defensive events found - check that sack_player_id/interception_player_id columns exist in the pbp data.")
        return

    player_season_value = compute_player_season_value(events)
    reference_season = int(player_season_value["season"].max())
    print(f"  Using {reference_season} as the reference season for recency weighting")

    print("Blending each player's portable career defensive value...")
    career_value = blend_player_career_value(player_season_value, reference_season)
    career_value.to_csv(os.path.join(PROCESSED_DIR, "player_defense_value.csv"), index=False)
    print(f"  Saved {len(career_value)} players to player_defense_value.csv")

    print("Computing each team's historical (personnel-attributed) defensive value...")
    team_value = compute_team_historical_value(player_season_value, reference_season)
    team_value.to_csv(os.path.join(PROCESSED_DIR, "team_historical_defense_value.csv"), index=False)
    print(f"  Saved {len(team_value)} teams to team_historical_defense_value.csv")

if __name__ == "__main__":
    main()
